# Generated by Django 2.2.7 on 2019-11-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_worksite_codes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
