# Generated by Django 2.2.7 on 2019-11-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20191127_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ManyToManyField(blank=True, null=True, related_name='_employee_manager_+', to='employee.Employee'),
        ),
    ]
